package ch16;

public class QX12 {

}

// Which statement about try-with-resources is not true?

// A. If the try block and close() method both throw an exception, the one
// thrown by the close() method is suppressed.

// B. A catch block is not required.

// C. If more than one resource is used, the resources are closed in the order
// they were created. (+)

// D. Parentheses are used for the resource declaration section, even if more
// than one resource is used.